[project]
name = "mxfold2"
version = "0.2.0"
description = "RNA secondary structure prediction using deep neural networks with thermodynamic integration"
authors = [
    { name="Kengo Sato", email="satoken@life.isct.ac.jp" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.2",
    "pybind11>=2.13.6",
    "pytorch-optimizer>=3.1.2",
    "torch>=2.4.1",
    "tqdm>=4.66.5",
    "pandas>=2.2",
    "rdkit>=2025.9.4",
]

[project.scripts]
mxfold2 = "mxfold2.__main__:main"

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "scipy>=1.14.1",
    "wandb>=0.18.0",
]

[tool.scikit-build]
cmake.source-dir = "./mxfold2/src"
sdist.include = ["mxfold2/models/*"]
sdist.exclude = [".devcontainer", ".gitignore", ".gitmodules", ".pylintrc"]
wheel.exclude = ["mxfold2/src"]